import pytest
import time
import threading
import redis
import json
from pymongo import MongoClient
# Import the updated publishing function from image_service
from services.image_service import publish_event


def test_full_pipeline():
    """
    End-to-end integration test:
    Image Event Trigger -> AI Mock Inference -> MongoDB Persistence.

    This test verifies that the event-driven chain correctly processes a
    submitted image and stores the enriched metadata into the database.
    """

    # 1. Database Setup: Initialize MongoDB connection and clear existing test data
    mongo_client = MongoClient('localhost', 27017)
    db = mongo_client['image_system']
    collection = db['annotations']
    collection.delete_many({})  # Ensure a clean state for the test
    print(" [TEST] MongoDB cleared.")

    # 2. Service Orchestration: Start downstream workers as background threads
    # In a production environment, these would be independent processes.
    from services.inference_service import start_inference_worker
    from services.db_service import start_db_worker

    # Initialize threads as daemons so they exit when the main test finishes
    inference_thread = threading.Thread(target=start_inference_worker, daemon=True)
    db_thread = threading.Thread(target=start_db_worker, daemon=True)

    inference_thread.start()
    db_thread.start()

    # Allow a brief delay for workers to establish Redis subscriptions
    time.sleep(2)

    # 3. Execution: Manually trigger the 'image.submitted' event
    # We simulate the payload that would normally be generated by the FastAPI upload endpoint
    test_image_id = "test_img_456"
    test_payload = {
        "image_id": test_image_id,
        "image_path": "/path/to/mock_image.jpg",
        "status": "test_trigger"
    }

    print(f" [TEST] Triggering event for {test_image_id}...")
    publish_event("image.submitted", test_payload)

    # 4. Latency Buffer: Wait for the asynchronous pipeline to finish processing
    # Inference (1.5s) + DB insertion time
    time.sleep(4)

    # 5. Verification: Query MongoDB to validate data integrity
    result = collection.find_one({"image_id": test_image_id})

    # Assertions to ensure the pipeline worked correctly
    assert result is not None, f"Test failed: No record found for {test_image_id} in MongoDB."

    # Note: Since our mock inference now picks random labels, we check if the label
    # exists and is within our expected pool.
    expected_labels = ["cat", "dog", "car", "bicycle", "person"]
    detected_label = result['annotations'][0]['label']

    assert detected_label in expected_labels, f"Unexpected label detected: {detected_label}"

    # Verify that下周需要的 numeric_id and vector were also stored
    assert "numeric_id" in result, "Missing numeric_id in stored document"

    print(f"!!! Full Pipeline Integration Test Passed for {test_image_id} !!!")
    print(f"Detected Label: {detected_label}")


if __name__ == "__main__":
    # Allow running the test script directly
    test_full_pipeline()